name: Update Markdown Performance
on:
  push:
    branches: [ main ]
    paths:
      - "**.md"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get List of Markdown Files
        id: getfile
        run: |
          # 주석 태그가 있고, 아직 성능 내용이 채워지지 않은(설명 문구만 있는) 파일 찾기
          find . -name "*.md" -print0 | while IFS= read -r -d $'\0' file; do
            if grep -q "" "$file" && grep -q "제출한 코드의 성능이 입력될 공간" "$file"; then
              echo "$file" >> not_filled_files.txt
            fi
          done

      - name: Update Performance in Markdown
        uses: dltkdgns00/BOJ-action@main
        with:
          path: not_filled_files.txt
          user_id: flyingdisc1

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Update performance details"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Cleanup
        if: always()
        run: rm -f not_filled_files.txt